-   id: run-python-tests
    name: Run Python tests
    description: Verify that Python tests pass. Files must be executable.
    entry: run-python-test-files.sh
    language: script
    files: '.*_test\.py'
